#define TINYGLTF_IMPLEMENTATION
#define STB_IMAGE_IMPLEMENTATION
#define STB_IMAGE_WRITE_IMPLEMENTATION

#include "tiny_gltf.h"

#define VMA_RECORDING_ENABLED 1
#define VMA_IMPLEMENTATION

#include "vk_mem_alloc.h"